// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASlCWDMXcGbIcKxmGB7YjKYpXztiUuq08',
    appId: '1:395298537210:web:050f27d6bed383404b5343',
    messagingSenderId: '395298537210',
    projectId: 'recycleapplearn',
    authDomain: 'recycleapplearn.firebaseapp.com',
    storageBucket: 'recycleapplearn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5wawlMSCLl8M51rJxNu8Svod05C429ok',
    appId: '1:395298537210:android:fe1653f56579dd5d4b5343',
    messagingSenderId: '395298537210',
    projectId: 'recycleapplearn',
    storageBucket: 'recycleapplearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvA5GDQLqF1QodnfwPLpVJj-CgnDB-ZQ4',
    appId: '1:395298537210:ios:864a33047293b4b54b5343',
    messagingSenderId: '395298537210',
    projectId: 'recycleapplearn',
    storageBucket: 'recycleapplearn.firebasestorage.app',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvA5GDQLqF1QodnfwPLpVJj-CgnDB-ZQ4',
    appId: '1:395298537210:ios:864a33047293b4b54b5343',
    messagingSenderId: '395298537210',
    projectId: 'recycleapplearn',
    storageBucket: 'recycleapplearn.firebasestorage.app',
    iosBundleId: 'com.example.recycleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASlCWDMXcGbIcKxmGB7YjKYpXztiUuq08',
    appId: '1:395298537210:web:77fd1c6d75a8b78b4b5343',
    messagingSenderId: '395298537210',
    projectId: 'recycleapplearn',
    authDomain: 'recycleapplearn.firebaseapp.com',
    storageBucket: 'recycleapplearn.firebasestorage.app',
  );
}
